---
libyaml/yaml-0.1.4.tgz:
  object_id: 9c006ee4-ef51-4d96-93e1-dfdccbc0b26f
  sha: !binary |-
    ZTBlNWUwOTE5MmFiMTBhNjA3ZTNkYTI5NzBkYjQ5MjExOGY1NjBmMg==
  size: 471759
ruby/bundler-1.2.1.gem:
  object_id: 458d4d9f-aa0e-488d-94d9-ca8b50d6dfb3
  sha: !binary |-
    MGNiZTZhZDdhNDFmMDY0ZDZjMTFjMTA1ODQ2NWZmZmIxYmQ1ODA2OQ==
  size: 226816
ruby/ruby-1.9.3-p448.tar.gz:
  object_id: 3fe8a983-f754-44c4-8694-0fba414eb5a7
  sha: !binary |-
    YzdmNzM2ZTNiYzFjYTFlNjYxOWE5MTIxODM3ZGQwODQwYWFkNzdjZQ==
  size: 12559260
ruby/rubygems-1.8.24.tgz:
  object_id: 824b70e4-8269-4e4b-a347-de17333f7971
  sha: !binary |-
    MzBmMjcwNDdlNzRmNzk0MzExNzczNmEwZDNlMjI0OTk0ZmVlMDkwNQ==
  size: 380101
libsqlite3/sqlite3_3.8.6.orig.tar.bz2:
  object_id: cb518c3a-5733-4be1-bafb-e04905c742a2
  sha: !binary |-
    Njk4MWE0MTE4OGMzZjFlZmU0NzllZWJjMDk4NjdhNDNhYjVhZWYyMw==
  size: 4039449
